In [1]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Getting Spotify Kaggle Data

In [4]:
#Spotify api no longer works.
filePath = '/content/drive/MyDrive/school classes/senior port/dataset.csv'
df = pd.read_csv(filePath)

In [7]:
df.info()
df = df.dropna()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 113999 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        113999 non-null  int64
 1   track_id          113999 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        113999 non-null  int64
 6   duration_ms       113999 non-null  int64
 7   explicit          113999 non-null  bool
 8   danceability      113999 non-null  float64
 9   energy            113999 non-null  float64
 10  key               113999 non-null  int64
 11  loudness          113999 non-null  float64
 12  mode              113999 non-null  int64
 13  speechiness       113999 non-null  float64
 14  acousticness      113999 non-null  float64
 15  instrumentalness  113999 non-null  float64
 16  liveness          113999 non-null  float64
 17  valence           113999 non-null  float64
 18  tempo             113999 non-null  float64
 19  time_signature    113999 non-null  int64
 20  track_genre       113999 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 18.4+ MB

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [8]:
df = df.drop(columns = "Unnamed: 0")
df.head(5)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

# Track ID's for my personal songs

In [34]:
import requests
import pandas as pd
from google.colab import files

In [ ]:
mySongs =[]

In [ ]:
url = "https://track-analysis.p.rapidapi.com/pktx/analysis"

querystring = {"song":"thinkingabtu","artist":"saraunh0ly"}

headers = {
}

response = requests.get(url, headers=headers, params=querystring)
mySongs.append(response.json())
print(mySongs)

[{'id': '8c060d0e68d661cb4e66e5b02d79b1e6', 'key': 'E', 'mode': 'major', 'camelot': '12B', 'tempo': 105, 'duration': '6:07', 'popularity': 54, 'energy': 70, 'danceability': 75, 'happiness': 34, 'acousticness': 85, 'instrumentalness': 89, 'liveness': 10, 'speechiness': 5, 'loudness': '-10 dB'}, {'id': 'f31699816bd21d591b62052fde690293', 'key': 'C#', 'mode': 'major', 'camelot': '3B', 'tempo': 156, 'duration': '2:22', 'popularity': 53, 'energy': 99, 'danceability': 51, 'happiness': 84, 'acousticness': 23, 'instrumentalness': 83, 'liveness': 11, 'speechiness': 8, 'loudness': '-5 dB'}, {'message': 'You have exceeded the DAILY quota for Requests on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/soundnet-soundnet-default/api/track-analysis'}]

In [ ]:
df = pd.DataFrame(mySongs)
df.to_csv('/content/drive/MyDrive/personal_spotify_data.csv', index=False)

# Data Preprocessing

In [39]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
filePath = '/content/drive/MyDrive/school classes/senior port/dataset.csv'
songDataset = pd.read_csv(filePath)
filePath2 = '/content/drive/MyDrive/school classes/senior port/personal_spotify_data.csv' 
personalDataset = pd.read_csv(filePath2)
# index 0 song: Magic Spells by Crystal Castles
# index 1 song: You Could Be The One by Snow Strippers

,id,key,mode,camelot,tempo,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
0,8c060d0e68d661cb4e66e5b02d79b1e6,E,major,12B,105,6:07,54,70,75,34,85,89,10,5,-10 dB
1,f31699816bd21d591b62052fde690293,C#,major,3B,156,2:22,53,99,51,84,23,83,11,8,-5 dB